### ISSUE TITLE
Support Forge 1.20.1

### ISSUE THREAD

**Issue by QarthO** [MinecraftAuthentication/plugin#7]
Any chance this could be updated to support Minecraft v1.20.1 on Forge?

**Comment by Scarsz** [comment]
Kind of an odd version, is there a mod pack that you’re using on that
version?

**Comment by QarthO** [comment]
Yup, ATM9 which arguably currently the most popular forge pack.

**Comment by Scarsz** [comment]
I’ll look into adding support in the next few days

**Comment by Scarsz** [comment]
https://github.com/MinecraftAuthentication/plugin/commit/f7362739d04d08f79de6b427b2ecc68b1fa92781
